routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('accueil');
Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');
Route::get('/',[HomeController::class,"index"])->name('home.index');
// Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
// Route::match(['get', 'post'], '/commandes/client/{id}', [CommandeController::class, "store"])->name('commande.store_client');

Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);


// Route::resource("categories",CategorieController::class);
// Route::resource("produits",ProduitController::class);
// Route::resource("clients",ClientController::class);
// Route::resource("commandes",CommandeController::class);

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        
        $produits=Produit::all([ 'id','designation','prix_u','quantite_stock',]);
        return view('home.index',compact('produits'));
    }
    public function add(Request $request,$id){
        $qte=$request->input('qte',1);
         $produit=Produit::find($id);
        $panier=$request->session()->get('panier',[]);
        if(isset($panier[$id])){
            $panier[$id]['qte']=$qte;
        }else{
        $panier[$id]=[
            'qte'=>$qte,
             'produit'=>$produit
        ];
    }
    
    $request->session()->put('panier',$panier);
    return redirect()->back();
        
    }
    public function show_panier(Request $request){
        $panier=$request->session()->get('panier',[]);
        $tot=0;
        foreach($panier as $id=>$item){
            $tot+=$item['qte']*$item['produit']->prix_u;
        }
        return view('home.panier',compact('panier','tot'));
    }
    public function delete(Request $request,$id){
        $panier=$request->session()->get('panier',[]);
        unset($panier[$id]);
        $request->session()->put('panier',$panier);
        return redirect()->back();
    }
    public function clear(Request $request ){

        $request->session()->forget('panier');
        // return redirect()->back();
        return redirect()->route('home.index');

    }
   
    
}

resources/views/home/index.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des categories')
 @section('content')
     
    <h1>Liste des Catalogues</h1>
    <div class="catalogue">
   
   @foreach ($produits as $item)
       <div class="item">
        <p>{{$item->designation}}</p>
        <p>Prix : {{$item->prix_u}} MAD</p>
        @if ($item->quantite_stock==0)
            <p>En repture de stock</p>
        @else
        <p>En stock : {{$item->quantite_stock}}</p>
        <form action="{{route('home.add',["id"=>$item->id])}}" method='POST'>
            @csrf
            <label for="qte">Quantite</label>
            <input type="number" name="qte" id="qte" min="1" max="{{$item->quantite_stock}}">
            <input type="submit" value="Acheter">
        </form>
          @endif
       </div>
 
   @endforeach
     
    </div>

@endsection

resources/views/home/panier.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des categories')
 @section('content')

@if (empty($panier))
    <p>Votre panier est vide</p>
@else
    <h1>Mon panier</h1>

  <table id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>Prix unitaire</th>
        <th>Quantite</th>
        <th>Total ligne</th>
        <th>Actions</th>
      </tr>
      @foreach ($panier as $id=> $item)
          <tr>
            <td>{{$id}}</td>
            <td>{{$item['produit']->designation}}</td>
            <td>{{$item['produit']->prix_u}}</td>
            <td>{{$item['qte']}}</td>
            <td>{{$item['qte']*$item['produit']->prix_u}} MAD</td>
            <td>
                <form action="{{route('home.delete',["id"=>$id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette ligne?')">
                </form></td>
          </tr>
      @endforeach
      <tr>
        <th colspan="4">Total</th>
        <td colspan="2">{{$tot}} MAD</td>
     </tr>
    </table>
  <a href="{{route('home.clear')}}">Vider le panier</a>
  <a href="{{route('clients.create')}}">Commander</a>
  @endif
@endsection