routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('accueil');
Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');
Route::get('/',[HomeController::class,"index"])->name('home.index');
// Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
// Route::match(['get', 'post'], '/commandes/client/{id}', [CommandeController::class, "store"])->name('commande.store_client');

Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);


// Route::resource("categories",CategorieController::class);
// Route::resource("produits",ProduitController::class);
// Route::resource("clients",ClientController::class);
// Route::resource("commandes",CommandeController::class);

resources/views/categories/create.blade.php
 @extends('layouts.admin')
 @section('title','Ajouter une categorie')
 @section('content')
    <h1>Créer une nouvelle categorie</h1>
    <form action="{{route('categories.store')}}" method="POST">
        @csrf
        <div class="form-group mb-3">
          <label class="mb-1"  for="designation">Designation</label>
          <input type="text" class="form-control name="designation" id="designation" value="{{old('designation')}}">
        </div>
         <div class="form-group mb-3">
        <label class="mb-1" for="description">Description</label>
       <textarea class="form-control mb-3" name="description" id="description"  rows="5" >{{old('designation')}}</textarea>

        </div>
        <div>
            <input class="btn btn-primary" type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <h6>Errors: </h6>
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>

           @endforeach
        </ul>
        @endif
    </div>
@endsection

resources/views/categories/edit.blade.php
 @extends('layouts.admin')
 @section('title','Modifier une categorie')
 @section('content')
    <h1>Modifier la categorie N° {{$cat->id}}</h1>
    <form action="{{route('categories.update',['category'=>$cat->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group mb-3">
        <label class="mb-1" for="designation">Designation</label>
        <input type="text" class="form-control" name="designation" id="designation" value="{{old('designation',$cat->designation)}}">
        </div>
        <div class="form-group mb-3">
        <label class="mb-1" for="description">Description</label>
        <textarea name="description" class="form-control" id="description" cols="30" rows="5" >{{old('designation',$cat->description)}}</textarea>

        </div>
        <div>
            <input class="btn btn-primary" type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>

           @endforeach
        </ul>



        @endif
    </div>

@endsection

resources/views/categories/index.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des categories')
 @section('content')
    <h1 class="my-2">Liste des categories</h1>
    <a class="btn btn-primary m-2" href="{{route('categories.create')}}">Ajouter une nouvelle categorie</a>
    <a class="btn btn-primary m-2" href="{{route('categories.recherche')}}">Rechercher de categorie</a>
    <table class="table" id="tbl">
      <tr >
        <th class="text-center">Id</th>
        <th >Designation</th>
        <th class="text-center">Description</th>
        <th class="text-center" colspan="3">Actions</th>
      </tr>
      @foreach ($categories as $cat)
          <tr>
            <td class="text-center">{{$cat->id}}</td>
            <td>{{$cat->designation}}</td>
            <td>{{$cat->description}}</td>
            <td class="text-center"><a class="btn btn-secondary" href="{{route('categories.show',['category'=>$cat->id])}}">Details</a></td>
            <td class="text-center"><a class="btn btn-success" href="{{route('categories.edit',['category'=>$cat->id])}}">Modifier</a></td>
            <td class="text-center">
                <form action="{{route('categories.destroy',['category'=>$cat->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input class="btn btn-danger" type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette categorie?')">
                </form></td>
          </tr>
      @endforeach
    </table>
    {{ $categories->links() }}
 @endsection

resources/views/categories/recherche.blade.php
<!-- resources/views/categories/recherche.blade.php -->

@extends('layouts.admin') <!-- Make sure to adjust the layout as per your application -->

@section('title', 'Recherche de catégorie')

@section('content')

    <h1>Recherche de catégorie</h1>

    <form action="{{ route('categories.recherche') }}" method="GET">
        @csrf

        <label for="designation">Designation:</label>
        <input type="text" name="designation" id="designation" required>

        <button type="submit">Rechercher</button>
    </form>

    @if(isset($cat))
        <div>
            <h2>Résultat de la recherche</h2>
            <p>ID: {{ $cat->id }}</p>
            <p>Designation: {{ $cat->designation }}</p>
            <p>Description: {{ $cat->description }}</p>
        </div>
        
    @else
    <div> designation non trouver</div>
        
    @endif
    

@endsection

resources/views/categories/show.blade.php
 @extends('layouts.admin')
 @section('title','Detail d \'une categorie')
 @section('content')
    <a class="btn btn-primary" href="{{route('categories.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie N° {{$cat->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$cat->designation}}</p>
        <p><strong>Description:</strong> {{$cat->description}}</p>
    </div>
@endsection