routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('accueil');
Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');
Route::get('/',[HomeController::class,"index"])->name('home.index');
// Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
// Route::match(['get', 'post'], '/commandes/client/{id}', [CommandeController::class, "store"])->name('commande.store_client');

Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);


// Route::resource("categories",CategorieController::class);
// Route::resource("produits",ProduitController::class);
// Route::resource("clients",ClientController::class);
// Route::resource("commandes",CommandeController::class);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>@yield('title','App store')</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav m-2">
            <li class="nav-item"><a class="nav-link" href="{{route('home.index')}}">Accueil</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('categories.index')}}">Gestion des categories</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('produits.index')}}">Gestion des produits</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('home.panier')}}">Gestion des panier</a></li>
            {{-- <li><a href="{{route('home.panier')}}">Mon panier</a></li> --}}
        </ul>
    </nav>
    <div class="main my-3 container-fluid">
        @yield('content')
    </div>
    <footer>
        &copy;OFPPT 2024
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>