routes/web.php
<?php

use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('accueil');
Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/categories/recherche', [CategorieController::class, 'recherche'])->name('categories.recherche');
Route::get('/',[HomeController::class,"index"])->name('home.index');
// Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
Route::post('/commandes/client/{id}',[CommandeController::class,"store"])->name('commande.store_client');
// Route::match(['get', 'post'], '/commandes/client/{id}', [CommandeController::class, "store"])->name('commande.store_client');

Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);


// Route::resource("categories",CategorieController::class);
// Route::resource("produits",ProduitController::class);
// Route::resource("clients",ClientController::class);
// Route::resource("commandes",CommandeController::class);

app/Models/Produit.php
<?php

namespace App\Models;

use App\Models\Categorie;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Produit extends Model
{
    use HasFactory;
    protected $fillable =[
        'designation',
        'prix_u',
        'quantite_stock',
        'categorie_id',
        'image',
    ];
    public function categorie(){
        return  $this->belongsTo(Categorie::class);
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $designation = $request->query('designation');
        $min_prix = $request->query('min_prix');
        $max_prix = $request->query('max_prix');
        $qnt_null = $request->query('qnt_null');
        $query_builder = Produit::query();
        if ($designation) {
            $query_builder->where('designation', 'like',    '%' . $designation . '%');
        }

        if ($qnt_null) {
            $query_builder->where('quantite_stock', '=', 0);
        }

        if ($min_prix && $max_prix) {
            $query_builder->whereBetween('prix_u', [$min_prix, $max_prix]);
        }
        $nbr_produit = count($query_builder->get());
        $produits = $query_builder->paginate(10)->appends(request()->query());


        return view("produits.index",compact('produits','designation','min_prix','max_prix','qnt_null','nbr_produit'));



    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories=Categorie::all();
        return view('produits.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $validateData = $request->validate([
            'designation'=>'required|unique:produits,designation',
            'prix_u'=>'required|integer|between:0,99999',
            'quantite_stock'=>'required|integer|between:1,9999',
            'categorie_id'=> 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        if($request->hasFile('image')){
            $imagePath = $request->file('image')->store('produits/images','public');
            $validateData['image'] = $imagePath;
        }
        // $validateData['image'] = $request->file('image')->store('produits/images','public');
        Produit::create($validateData);
        return  redirect()->route('produits.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $pro=Produit::find($id);

        return view('produits.show')->with("pro",$pro);
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $categories=Categorie::all();
        $pro=Produit::find($id);
        return view('produits.edit',compact('pro','categories'));
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'designation'=>'required|unique:produits,designation',
            'prix_u'=>'required|integer|between:0,99999',
            'quantite_stock'=>'required|integer|between:1,9999',
            'categorie_id'=> 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
       ]);
        $pro=Produit::find($id);
        $pro->update($request->all());
        return redirect()->route('produits.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');

        //
    }
}

resources/views/produits/create.blade.php
@extends('layouts.admin')
@section('title','Ajouter une produit')
@section('content')
    <h1>Créer une nouvelle produit</h1>
    <form  action="{{route('produits.store')}}" enctype="multipart/form-data" method="POST">
        @csrf
          <div class="form-group mb-3">
            <label class="mb-1" for="designation">Designation</label>
            <input type="text" class="form-control" name="designation" id="designation" value="{{old('designation')}}">
          </div>
          <div class="form-group mb-3">
            <label class="mb-1" for="prix_u">prix_u</label>
            <input type="text" class="form-control" name="prix_u" id="prix_u" value="{{old('prix_u')}}">
          </div>
          <div class="form-group mb-3">
            <label class="mb-1" for="quantite_stock">quantite_stock</label>
            <input type="text" class="form-control" name="quantite_stock" id="quantite_stock" value="{{old('quantite_stock')}}">
          </div>
          <div class="form-group mb-3">
            <label class="mb-1" for="categorie_id">Choose a categorie_id:</label>
            <select class="form-control" name="categorie_id" id="categorie_id">
              @foreach ($categories as $cat)
              <option value="{{$cat->id}}">{{$cat->id}}</option>
              @endforeach
            </select>
          </div>
            <div class="form-group mb-3">
              <label class="mb-1" for="image">Select Image</label>
              <input type="file" class="form-control" name="image" id="image">
            </div>

          <div>
              <input class="btn btn-primary" type="submit" value="Ajouter">
          </div>
    </form>
    <div>
        @if($errors->any())
        <h6>Errors: </h6>
        <ul>
          @foreach($errors->all() as $er)
          <li>{{$er}}</li>
          @endforeach
        </ul>



        @endif
    </div>
@endsection

resources/views/produits/edit.blade.php
@extends('layouts.admin')
 @section('title','Modifier une produit')
 @section('content')
    <h1>Modifier la produit N° {{$pro->id}}</h1>
    <form action="{{route('produits.update',['produit'=>$pro->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group mb-3">
        <label class="mb-1" for="designation">Designation</label>
        <input type="text" class="form-control" name="designation" id="designation" value="{{old('designation',$pro->designation)}}">
        </div>
        <div class="form-group mb-3">
        <label class="mb-1" for="prix_u">prix_u</label>
        <input type="text" class="form-control" name="prix_u" id="prix_u" value="{{old('prix_u',$pro->prix_u)}}">
        </div>
        <div class="form-group mb-3">
        <label class="mb-1" for="quantite_stock">quantite_stock</label>
        <input type="text" class="form-control" name="quantite_stock" id="quantite_stock" value="{{old('quantite_stock',$pro->quantite_stock)}}">
        </div>
        <div class="form-group mb-3">
        <label class="mb-1" for="categorie_id">Choose a categorie_id:</label>
        <select class="form-control" name="categorie_id" id="categorie_id">
        @foreach ($categories as $cat)

          <option value="{{ $cat->id }}" {{ ( $pro->categorie_id == $cat->id) ? 'selected' : '' }}>
                {{ $cat->id }}
            </option>

          @endforeach
        </select>

        </div>

        <div>
            <input class="btn btn-primary" type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>

           @endforeach
        </ul>



        @endif
    </div>
@endsection

resources/views/produits/index.blade.php
@extends('layouts.admin')
 @section('title','Gestion des produits')
 @section('content')

 <h1 class="my-2">Recherche de produit</h1>

 <form action="{{ route('produits.index') }}" method="GET">
     @csrf

        <div class="input-group m-3">
         <div class="input-group-prepend">
           <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">Designation</span>
         </div>
         <input class="col-xs-5 border border-secondary  div-inputs" type="text" class="form-control" name="designation" id="designation" value="{{old('designation',$designation)}}" aria-describedby="basic-addon3">
        <div class="input-group-prepend ">
          <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">Prix_min</span>
        </div>
        <input class="col-xs-5 border border-secondary " type="text" class="form-control" name="min_prix" id="designation" value="{{old('min_prix',$min_prix)}}" aria-describedby="basic-addon3">
        <div class="input-group-prepend ">
            <span class="input-group-text rounded-0 border border-secondary" id="basic-addon3">Prix_max</span>
          </div>
          <input class="col-xs-5 border border-secondary div-inputs" type="text" class="form-control" name="max_prix" id="designation" value="{{old('max_prix',$max_prix)}}" aria-describedby="basic-addon3">
          <div class="input-group-prepend ">
            <div class="input-group-text">
              <input class="mx-2" type="checkbox" name="qnt_null" aria-label="Checkbox for following text input">
              <label for="checkbox" class="div-inputs" >Produits ayant un quantité nulle</label>
            </div>
          </div>
          <button class="btn btn-primary mx-3" type="submit">Rechercher</button>
      </div>
    </form>


    <h1 class="my-2">Liste des produits</h1>
    <a class="btn btn-primary m-2" href="{{route('produits.create')}}">Ajouter une nouvelle produit</a>

    <div class="custom-container ml-5 ">
      Résultats : <span class="badge bg-primary m-2"> {{$nbr_produit}}</span></div>
    <table class="table" id="tbl">
      <tr class="text-center">
        <th>Id</th>
        <th>Designation</th>
        <th>prix_u</th>
        <th>quantite_stock</th>
        <th>categorie_id</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($produits as $pro)
          <tr>
            <td class="text-center">{{$pro->id}}</td>
            <td>{{$pro->designation}}</td>
            <td class="text-center">{{$pro->prix_u}}</td>
            <td class="text-center">{{$pro->quantite_stock}}</td>
            <td class="text-center">{{$pro->categorie_id}}</td>
            <td class="text-center"><a class="btn btn-secondary" href="{{route('produits.show',['produit'=>$pro->id])}}">Details</a></td>
            <td class="text-center"><a class="btn btn-success" href="{{route('produits.edit',['produit'=>$pro->id])}}">Modifier</a></td>
            <td class="text-center">
                <form action="{{route('produits.destroy',['produit'=>$pro->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input class="btn btn-danger" type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette produit?')">
                </form></td>
          </tr>
      @endforeach
    </table>
    {{ $produits->links() }}
 @endsection

resources/views/produits/show.blade.php
@extends('layouts.admin')
 @section('title','Detail d \'une produit')
 @section('content')
    <a class="btn btn-primary" href="{{route('produits.index')}}">Retourner vers la liste des produits</a>
    <h1>Détail de la produit N° {{$pro->id}}</h1>
    <div>
        @if ($pro->image)

                <img src="{{ asset('storage/' . $pro->image) }}" alt="Product Image">
            @endif
        <p><strong>Designation:</strong> {{$pro->designation}}</p>
        <p><strong>prix_u:</strong> {{$pro->prix_u}}</p>
        <p><strong>quantite_stock:</strong> {{$pro->quantite_stock}}</p>
        <p><strong>categorie_id:</strong> {{$pro->categorie_id}}</p>
    </div>
@endsection